// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int64  `json:"id"`
	UserID    int64  `json:"user_id"`
	ProductID int64  `json:"product_id"`
	Texts     string `json:"texts"`
}

type CommentMedium struct {
	ID        int64 `json:"id"`
	CommentID int64 `json:"comment_id"`
	FileID    int64 `json:"file_id"`
}

type Commodity struct {
	ID     int64  `json:"id"`
	Name   string `json:"name"`
	UserID int64  `json:"user_id"`
	Price  string `json:"price"`
	Texts  string `json:"texts"`
	IsFree bool   `json:"is_free"`
	IsLend bool   `json:"is_lend"`
}

type CommodityMedium struct {
	ID          int64 `json:"id"`
	CommodityID int64 `json:"commodity_id"`
	FileID      int64 `json:"file_id"`
}

type File struct {
	ID       int64     `json:"id"`
	Filename string    `json:"filename"`
	FileKey  string    `json:"file_key"`
	Url      string    `json:"url"`
	Userid   int64     `json:"userid"`
	CreateAt time.Time `json:"create_at"`
}

type LendTime struct {
	ID        int64  `json:"id"`
	ProductID int64  `json:"product_id"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

type Message struct {
	ID       int64     `json:"id"`
	Fid      int64     `json:"fid"`
	Tid      int64     `json:"tid"`
	IsFile   bool      `json:"is_file"`
	IsRead   bool      `json:"is_read"`
	Texts    string    `json:"texts"`
	Createat time.Time `json:"createat"`
}

type Order struct {
	ID             int64     `json:"id"`
	OrderID        string    `json:"order_id"`
	LendUserID     int64     `json:"lend_user_id"`
	BorrowUserID   int64     `json:"borrow_user_id"`
	ProductID      int64     `json:"product_id"`
	UnitPrice      string    `json:"unit_price"`
	TotalPrice     string    `json:"total_price"`
	CompletionTime string    `json:"completion_time"`
	ProductStatus  int32     `json:"product_status"`
	ExpressNumber  string    `json:"express_number"`
	StartTime      time.Time `json:"start_time"`
	EndTime        time.Time `json:"end_time"`
}

type ProductTag struct {
	ProductID int64 `json:"product_id"`
	TagID     int64 `json:"tag_id"`
}

type Tag struct {
	TagID   int64  `json:"tag_id"`
	TagName string `json:"tag_name"`
}

type User struct {
	ID       int64          `json:"id"`
	Name     string         `json:"name"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Avatar   string         `json:"avatar"`
	Sign     string         `json:"sign"`
	Gender   string         `json:"gender"`
	Birthday string         `json:"birthday"`
	Address  sql.NullString `json:"address"`
}

type UserLike struct {
	ID        int64 `json:"id"`
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
}
