// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) error
	ExistEmail(ctx context.Context, email string) (bool, error)
	GetUserByUsername(ctx context.Context, name string) (User, error)
}

var _ Querier = (*Queries)(nil)
